<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.8.2.4 setup script by Michal ?iha? <michal@cihar.com>
 * Version: $Id: setup.php,v 1.23.2.10.2.4 2006/08/22 17:36:34 lem9 Exp $
 * Date: Thu, 09 Nov 2006 07:49:44 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */
?>
