<?php
$dir_tbl = array(
	array('id' => 1, 'name' => '受信トレイ', 'tree_level' => 1, 'parent_id' => 0),
	array('id' => 2, 'name' => '保存', 'tree_level' => 1, 'parent_id' => 0),
	array('id' => 3, 'name' => '送信済み', 'tree_level' => 1, 'parent_id' => 0),
	array('id' => 4, 'name' => '削除済み', 'tree_level' => 1, 'parent_id' => 0),
	array('id' => 5, 'name' => '退会', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 6, 'name' => '配信停止', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 7, 'name' => 'キャンセル', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 8, 'name' => 'デジタルチェック', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 9, 'name' => '金返せ', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 10, 'name' => '楽天銀行', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 11, 'name' => 'ﾁｪｯｸ済み[ﾌﾟﾚｾﾞﾝﾄ]', 'tree_level' => 2, 'parent_id' => 2),
	array('id' => 12, 'name' => '商品発送先住所', 'tree_level' => 2, 'parent_id' => 2),
	array('id' => 13, 'name' => '住所ﾁｪｯｸ済み', 'tree_level' => 3, 'parent_id' => 12),
	array('id' => 14, 'name' => 'ｸﾚｰﾑ・要注意', 'tree_level' => 2, 'parent_id' => 2),
	array('id' => 15, 'name' => 'ZERO　広告系', 'tree_level' => 2, 'parent_id' => 2),
	array('id' => 16, 'name' => '良い情報が出たらね！！クレーム客', 'tree_level' => 2, 'parent_id' => 2),
	array('id' => 17, 'name' => 'コンビニダイレクトエラー', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 18, 'name' => 'クレジット、コンビニ決済緊急避難所', 'tree_level' => 3, 'parent_id' => 12),
	array('id' => 19, 'name' => 'インフォバリュー', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 20, 'name' => '【諸官庁】要注意!!', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 21, 'name' => '個体識別（元はラグジュアリーロト６用）', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 22, 'name' => 'サブフォルダ名', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 23, 'name' => '手動入金', 'tree_level' => 3, 'parent_id' => 22),
	array('id' => 24, 'name' => 'ポイントで参加不可！！', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 25, 'name' => '不要', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 26, 'name' => 'システムがわかっていない。注意が必要', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 27, 'name' => '放置', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 28, 'name' => 'あぶない感じ　　　　', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 29, 'name' => 'ペイデザイン入金通知', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 30, 'name' => '井坂さんへの質問', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 31, 'name' => '最後の特別情報', 'tree_level' => 2, 'parent_id' => 1),
	array('id' => 32, 'name' => 'ga10001', 'tree_level' => 2, 'parent_id' => 1),
);
?>
